language: scala
jdk: oraclejdk9
scala:
- 2.10.7
- 2.11.12
script:
- java -version
- wget http://www.scala-lang.org/files/archive/scala-${TRAVIS_SCALA_VERSION}.zip
- unzip scala-${TRAVIS_SCALA_VERSION}.zip
- chmod +x ./scala-${TRAVIS_SCALA_VERSION}/bin/scalac
- ./scala-${TRAVIS_SCALA_VERSION}/bin/scalac -nobootcp A.scala
